import { VerificationStatus } from './user';

export interface Song {
  id: string;
  title: string;
  artist: string;
  artists?: string[];
  artistIds?: string[];
  userId: string;
  genre: string;
  releaseDate: string | null;
  audioUrl?: string;
  soundcloudUrl: string | null;
  soundcloudEmbed?: string;
  imageUrl?: string;
  isFavorite: boolean;
  uploadDate: string;
  createdAt?: string;
  favoritedBy?: string[];
  favoritedAt?: Date[];
  favoriteCount: number;
  updatedAt: string;
  verificationStatus: VerificationStatus;
  confirmations: number;
  confirmedBy: string[];
  confirmedAt: Date[];
  reports: number;
  reportedBy: string[];
  reportedAt: Date[];
  submittedBy: string;
  submittedAt: Date;
  lastEditedBy?: string;
  lastEditedAt?: Date;
  version: number;
  notes?: string;
  isHidden: boolean;
  hiddenReason?: string;
  hiddenBy?: string;
  hiddenAt?: Date;
  upvotes: string[];
  downvotes: string[];
}
